function(InstallSharedLibrary)
  cmake_parse_arguments(INSTALL_SHARED "" "TARGET" "" ${ARGN})

  install(TARGETS ${INSTALL_SHARED_TARGET}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  )
endfunction()

function(InstallModuleLibrary)
  cmake_parse_arguments(INSTALL_MODULE "" "TARGET;DESTINATION" "" ${ARGN})

  install(TARGETS ${INSTALL_MODULE_TARGET}
    RUNTIME DESTINATION ${INSTALL_MODULE_DESTINATION}
    LIBRARY DESTINATION ${INSTALL_MODULE_DESTINATION}
  )
endfunction()